packages:
  - "packages/*"
  - "apps/*"

catalog:
  vite: ^5.4.9
  vitest: ^2.1.3
  svelte: 5.0.0-next.268
  "@sveltejs/vite-plugin-svelte": ^4.0.0-next.8
  svelte-check: ^4.0.5
  "@tsconfig/svelte": ^5.0.4
  ajv: ^8.17.1
