packages:
  - "packages/*"
  - "apps/*"

catalog:
  vite: ^5.4.8
  vitest: ^2.1.2
  # NOTE: `svelte-package` does not support `catalog:` protocol
  #       so svelte version update should be duplicated in `form` package
  svelte: 5.0.0-next.264
  "@sveltejs/vite-plugin-svelte": ^4.0.0-next.7
  svelte-check: ^4.0.4
  "@tsconfig/svelte": ^5.0.4
  ajv: ^8.17.1
