packages:
  - "packages/*"
  - "apps/*"

catalog:
  ajv: "^8.17.1"
  vite: "5.4.11"
  vitest: "2.1.5"
  svelte: "^5.2.0"
  "@sveltejs/kit": "^2.8.1"
  "@sveltejs/adapter-static": "^3.0.6"
  "@sveltejs/package": "^2.3.7"
  "@sveltejs/vite-plugin-svelte": "^4.0.0"
  svelte-check: "^4.0.7"
  "@tsconfig/svelte": "^5.0.4"
  "@playwright/test": "^1.48.2"
  "@types/eslint": "^9.6.1"
  "autoprefixer": "^10.4.20"
  "eslint": "^9.14.0"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-svelte": "^2.46.0"
  "globals": "^15.12.0"
  "postcss": "^8.4.49"
  "prettier": "^3.3.3"
  "prettier-plugin-svelte": "^3.2.8"
  "tailwindcss": "^3.4.15"
  "typescript-eslint": "^8.14.0"
  "zod": "^3.23.8"