packages:
  - "packages/*"
  - "apps/*"

catalog:
  ajv: "^8.0.0"
  vite: "5.4.10"
  vitest: "2.1.3"
  svelte: "^5.1.9"
  "@sveltejs/kit": "^2.7.3"
  "@sveltejs/adapter-static": "^3.0.5"
  "@sveltejs/package": "^2.3.7"
  "@sveltejs/vite-plugin-svelte": "^4.0.0"
  svelte-check: "^4.0.5"
  "@tsconfig/svelte": "^5.0.4"
  "@playwright/test": "^1.48.2"
  "@types/eslint": "^9.6.1"
  "autoprefixer": "^10.4.20"
  "daisyui": "^4.12.13"
  "eslint": "^9.13.0"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-svelte": "^2.46.0"
  "globals": "^15.11.0"
  "postcss": "^8.4.47"
  "prettier": "^3.3.3"
  "prettier-plugin-svelte": "^3.2.7"
  "tailwindcss": "^3.4.14"
  "typescript-eslint": "^8.11.0"