packages:
  - "packages/*"
  - "apps/*"

catalog:
  vite: 5.4.9
  vitest: 2.1.3
  svelte: ^5.0.0
  "@sveltejs/vite-plugin-svelte": ^4.0.0
  svelte-check: ^4.0.5
  "@tsconfig/svelte": ^5.0.4
  ajv: ^8.0.0
